import type R from "react";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReportProvider } from "@/lib/store";

export const metadata = {
  title: "REPORT_EDITOR // BRUTALIST_v1.0_CN_AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: R.ReactNode;
}) {
  return (
    <html className="light" lang="zh-CN">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700;800&family=Noto+Sans+SC:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn(
          "h-screen flex flex-col overflow-hidden border-4 border-black font-mono"
        )}
      >
        <ReportProvider>
          {children}
        </ReportProvider>
      </body>
    </html>
  );
}
